
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel
      - env: 
          MAVEN_USER: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: bazel run --stamp --define "maven_repo=https://oss.sonatype.org/service/local/staging/deploy/maven2" --define gpg_sign=true //src/main/proto/wfa/measurement/api/v2alpha:exported_lib`

      # - name: Upload a Build Artifact
      #   uses: actions/upload-artifact@v4.3.1
      #   with:
      #     name: proto_jars
      #     path: bazel-bin/src/main/proto/wfa/measurement/api/v2alpha
      #     overwrite: true
          
