
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel build //src/main/proto/wfa/measurement/api/v2alpha:java_proto

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: proto_jars
          path: bazel-bin/src/main/proto/wfa/measurement/api/v2alpha
          overwrite: true
          
