
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Publish edp jar
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: bazel run --stamp --define "maven_repo=https://s01.oss.sonatype.org/service/local/staging/deploy/maven2" --define gpg_sign=true //src/main/proto/wfa/measurement/api/v2alpha:exported_lib.publish
